version: '3.3'
services:
    backend:
        # image: ghcr.io/nrgbistro/vari-wordle/server:latest-dev
        build:
            context: ./server
            dockerfile: Dockerfile
        container_name: vari-wordle-dev-server
        env_file:
            - server/.env
        ports:
            - '3001:3001'
        networks:
          - vari-wordle-net
    frontend:
        # image: ghcr.io/nrgbistro/vari-wordle/client:latest-dev
        build:
            context: ./client
            dockerfile: Dockerfile
        container_name: vari-wordle-dev-client
        ports:
            - '3000:80'
        depends_on:
            - backend
        restart: unless-stopped
        networks:
          - vari-wordle-net

networks:
  vari-wordle-net:
    external: true