version: '3.3'
services:
    backend:
        build:
            context: ./server
            dockerfile: Dockerfile
        container_name: vari-wordle-dev-server
        env_file:
            - server/.env
        ports:
            - '3001:3001'
        # image: vari-wordle-dev-server
        networks:
          - vari-wordle-net
    frontend:
        build:
            context: ./client
            dockerfile: Dockerfile
        container_name: vari-wordle-dev-client
        ports:
            - '3000:3000'
        depends_on:
            - backend
        restart: unless-stopped
        # image: vari-wordle-dev-client
        networks:
          - vari-wordle-net

networks:
  vari-wordle-net:
    external: true