name: Docker Image CI Production

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build_client:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: "main"

      - name: Get Package Version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main
        with:
          path: "./client"

      - name: Build Docker image
        run: docker build -t ghcr.io/nrgbistro/vari-wordle/client:latest -t ghcr.io/nrgbistro/vari-wordle/client:${{steps.package-version.outputs.current-version}} .

      - name: Login to ghcr.io
        run: docker login ghcr.io -u nrgbistro -p ${{ secrets.GHCR_PASSWORD }}

      - name: Push image to ghcr.io
        run: docker push -a ghcr.io/nrgbistro/vari-wordle/client

  build_server:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: "main"

      - name: Get Package Version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main
        with:
          path: ./server

      - name: Build Docker image
        run: docker build -t ghcr.io/nrgbistro/vari-wordle/server:latest -t ghcr.io/nrgbistro/vari-wordle/server:${{steps.package-version.outputs.current-version}} .

      - name: Login to ghcr.io
        run: docker login ghcr.io -u nrgbistro -p ${{ secrets.GHCR_PASSWORD }}

      - name: Push image to ghcr.io
        run: docker push -a ghcr.io/nrgbistro/vari-wordle/server
